import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import connectMongo, { dbConnect } from "@/services/mongo";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Evenza",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect()
  // console.log("MONGO_URI:", process.env.MONGO_URI);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
